Testing manual release w/ tags

diff --git a/.github/workflows/manual-release.yml b/.github/workflows/manual-release.yml
--- a/.github/workflows/manual-release.yml
+++ b/.github/workflows/manual-release.yml
@@ -14,6 +14,34 @@ on:
         required: false
 
 jobs:
+  tag-version:
+    name: Tag Version
+    runs-on: ubuntu-latest
+    outputs:
+      old_version: ${{ steps.bumpversion.outputs.old_ver }}
+      version: ${{ steps.bumpversion.outputs.new_ver }}
+    # Validate bump part before moving forward 
+    if: contains(['major', 'minor', 'patch'], ${{ github.event.inputs.bumpPart }})
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v2
+
+      - name: Bump version and push tag
+        id: bumpversion
+        uses: jaumann/github-bumpversion-action@v0.0.7
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DEFAULT_BUMP: ${{ github.event.inputs.bumpPart }}
+      # - name: Testing bumping
+      #   run: |
+      #     echo "Old version: ${{ steps.bumpversion.outputs.old_ver }}"
+      #     echo "New version: ${{ steps.bumpversion.outputs.new_ver }}"
+      #     echo "Bump type: ${{ steps.bumpversion.outputs.part }}"
+      - name: Push tags
+        run: |
+          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
+          git push "${remote_repo}" HEAD:${GITHUB_REF} --follow-tags --tags
+
   build:
       name: Build app
       runs-on: ubuntu-latest
@@ -34,108 +62,53 @@ jobs:
             name: app_tgz
             path: dist/demo-splunkapp.tgz
 
-  # tag-version:
-  #   name: Tag Version
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     old_version: ${{ steps.bumpversion.outputs.old_ver }}
-  #     version: ${{ steps.bumpversion.outputs.new_ver }}
-  #   # Validate bump part before moving forward 
-  #   if: contains(['major', 'minor', 'patch'], ${{ github.event.inputs.bumpPart }})
-  #   steps:
-  #     - name: Checkout source
-  #       uses: actions/checkout@v2
-
-  #     - name: Bump version and push tag
-  #       id: bumpversion
-  #       uses: jaumann/github-bumpversion-action@v0.0.7
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #         DEFAULT_BUMP: ${{ github.event.inputs.bumpPart }}
-  #     # - name: Testing bumping
-  #     #   run: |
-  #     #     echo "Old version: ${{ steps.bumpversion.outputs.old_ver }}"
-  #     #     echo "New version: ${{ steps.bumpversion.outputs.new_ver }}"
-  #     #     echo "Bump type: ${{ steps.bumpversion.outputs.part }}"
-  #     - name: Push tags
-  #       run: |
-  #         remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
-  #         git push "${remote_repo}" HEAD:${GITHUB_REF} --follow-tags --tags
-
-  # release:
-  #   name: Create Release
-  #   needs: 
-  #     - build
-  #     - tag-version
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
-      
-  #     - name: Fetch all tags
-  #       run: |
-  #         git fetch --unshallow --tags
-
-  #     - name: Build changelog message
-  #       id: changelog
-  #       run: |
-  #         tags_no=$(git tag -l | wc -l)
-  #         if [[ "${tags_no}" > 1 ]]; then 
-  #           content=$(git log v${{ needs.tag-version.outputs.old_version }}..v${{ needs.tag-version.outputs.version }} --oneline --decorate --pretty=format:"%s" | tail -n 1)
-  #           content="${content//'%'/%25}"
-  #           content="${content//$'\n'/%0A}"
-  #           content="${content//$'\r'/%0D}"
-  #         else
-  #           content="Initial release"
-  #         fi
-  #         echo "::set-output name=message::${content}" 
-
-  #     # - name: Testing changelog
-  #     #   run: echo "${{ steps.changelog.outputs.message }}"
-      
-  #     - name: Create Release
-  #       id: create_release
-  #       uses: actions/create-release@v1
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       with:
-  #         tag_name: v${{ needs.tag-version.outputs.version }}
-  #         release_name: v${{ needs.tag-version.outputs.version }}
-  #         body: |
-  #           ## Changelog
-  #           ${{ github.event.inputs.notes }}
-
-  #           ${{ steps.changelog.outputs.message }}
-  #         draft: false
-  #         prerelease: false
-
-  #     - name: Download artifact
-  #       uses: actions/download-artifact@v2
-  #       with:
-  #         name: app_tgz
-      
-  #     - name: Get artifact name
-  #       id: app-name
-  #       run: |
-  #         app_package=$(ls -1 *gz | xargs basename)
-  #         echo "::set-output name=package::${app_package}"
-      
-  #     - name: Upload Release Asset
-  #       id: upload-release-asset 
-  #       uses: actions/upload-release-asset@v1
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       with:
-  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
-  #         asset_path: ${{ steps.app-name.outputs.package }}
-  #         asset_name: ${{ steps.app-name.outputs.package }}
-  #         asset_content_type: application/tgz
-
-  publish:
-    needs: build
-    name: Upload to Splunkbase
+  release:
+    name: Create Release
+    needs: 
+      - build
+      - tag-version
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Fetch all tags
+        run: |
+          git fetch --unshallow --tags
+
+      - name: Build changelog message
+        id: changelog
+        run: |
+          tags_no=$(git tag -l | wc -l)
+          if [[ "${tags_no}" > 1 ]]; then 
+            content=$(git log v${{ needs.tag-version.outputs.old_version }}..v${{ needs.tag-version.outputs.version }} --oneline --decorate --pretty=format:"%s" | tail -n 1)
+            content="${content//'%'/%25}"
+            content="${content//$'\n'/%0A}"
+            content="${content//$'\r'/%0D}"
+          else
+            content="Initial release"
+          fi
+          echo "::set-output name=message::${content}" 
+
+      # - name: Testing changelog
+      #   run: echo "${{ steps.changelog.outputs.message }}"
+      
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: v${{ needs.tag-version.outputs.version }}
+          release_name: v${{ needs.tag-version.outputs.version }}
+          body: |
+            ## Changelog
+            ${{ github.event.inputs.notes }}
+
+            ${{ steps.changelog.outputs.message }}
+          draft: false
+          prerelease: false
+
       - name: Download artifact
         uses: actions/download-artifact@v2
         with:
@@ -146,21 +119,48 @@ jobs:
         run: |
           app_package=$(ls -1 *gz | xargs basename)
           echo "::set-output name=package::${app_package}"
+      
+      - name: Upload Release Asset
+        id: upload-release-asset 
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ steps.app-name.outputs.package }}
+          asset_name: ${{ steps.app-name.outputs.package }}
+          asset_content_type: application/tgz
 
-      - name: Test connectivity
-        run: |
-          if ! ${{ secrets.SPLUNKBASE_ID != '' }} ; then exit 1; fi
-          curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request GET "https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/"
+  # publish:
+  #   needs: release
+  #   name: Upload to Splunkbase
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: app_tgz
+      
+  #     - name: Get artifact name
+  #       id: app-name
+  #       run: |
+  #         app_package=$(ls -1 *gz | xargs basename)
+  #         echo "::set-output name=package::${app_package}"
 
-      # Following docs: https://dev.splunk.com/enterprise/docs/releaseapps/splunkbase/submitcontentui/#Submit-content-to-Splunkbase-with-the-Release-API
-      - name: "Uploading on Splunkbase"
-        if: ${{ success() }}
-        run: |
-          mkdir build
-          tar -xf ${{ steps.app-name.outputs.package }} -C build
-          PACKAGE=$(ls build/*)
-          echo $PACKAGE
-          echo ${{ steps.app-name.outputs.package }}
-          source .splunkbase
+  #     - name: Test connectivity
+  #       run: |
+  #         if ! ${{ secrets.SPLUNKBASE_ID != '' }} ; then exit 1; fi
+  #         curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request GET "https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/"
+
+  #     # Following docs: https://dev.splunk.com/enterprise/docs/releaseapps/splunkbase/submitcontentui/#Submit-content-to-Splunkbase-with-the-Release-API
+  #     - name: "Uploading on Splunkbase"
+  #       if: ${{ success() }}
+  #       run: |
+  #         mkdir build
+  #         tar -xf ${{ steps.app-name.outputs.package }} -C build
+  #         PACKAGE=$(ls build/*)
+  #         echo $PACKAGE
+  #         echo ${{ steps.app-name.outputs.package }}
+  #         source .splunkbase
           
-        # curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request POST https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/new_release/ -F "files[]=@${PACKAGE}" -F "filename=${{ steps.app-name.outputs.package }}" -F "splunk_versions=${{ secrets.SPLUNKBASE_SPLUNK_VERSION }}" -F "visibility=true"  
+  #       # curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request POST https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/new_release/ -F "files[]=@${PACKAGE}" -F "filename=${{ steps.app-name.outputs.package }}" -F "splunk_versions=${{ secrets.SPLUNKBASE_SPLUNK_VERSION }}" -F "visibility=true"  
